### ISSUE TITLE
Use snmpfwd as a proxy (non-transparent) with contexts?

### ISSUE THREAD

**Issue by aseques** [etingof/snmpfwd#15]
Hello, I am trying to get snmp information for some hosts that are behind a DMZ, in the past i used snmpv3 context features (net-snmp), but it's not very well documented and I run into some issues, also I would like to forward traps to my monitoring server (zenoss), so snmpfw might be a good alternative.
I've seen the examples on using the trap forwarding feature, but I haven't seen about the snmp forwarding. Is there any example of this?

monitoring server -> linux server (sees both networks) -> serverA , serverB

**Comment by etingof** [comment]
Absolutely, you should be able to forward both [SNMP commands](https://snmpfwd.sourceforge.io/configuration/examples/command-forwarding-snmpv3-to-snmpv1.html) and [notifications](https://snmpfwd.sourceforge.io/configuration/examples/trap-forwarding-snmpv2.html). 

You can change SNMP version when forwarding, though this is a side-feature which you may ignore. That is you can forward commands/notifications in a 1-to-1 fashion SNMP version-wise. 

Let me know if something is still not clear enough.
