### ISSUE TITLE
SNMP v1 Traps Missing Vars

### ISSUE THREAD

**Issue by apsivam** [etingof/snmpfwd#26]
Received v1 traps are getting converted to v2c [here](https://github.com/etingof/snmpfwd/blob/9ab1d0d61cf8d7d0ada6c5ca4f1bddcab44c5e38/scripts/snmpfwd-server.py#L211) and in [next line](https://github.com/etingof/snmpfwd/blob/9ab1d0d61cf8d7d0ada6c5ca4f1bddcab44c5e38/scripts/snmpfwd-server.py#L214) setDefaults is getting called. setDefaults clears/empties all existing vars on the trap a new instance of trap object gets created with default vars.

Please check and confirm if this is a bug.

Configurations: nothing special. Send a v1 trap to snmpfwd-server and snmpfwd-client and any external manager only receive a trap with default vars not the ones sent.

**Comment by etingof** [comment]
This looks like a bug. I guess you've tried to flip these lines over already and it worked for you?

Are you planning a PR fixing this? ;)

**Comment by apsivam** [comment]
Created a [PR](https://github.com/etingof/snmpfwd/pull/27) with a work around that worked for me, but I'm sure there is another proper way of handling this problem :)

**Comment by etingof** [comment]
Thank you!
