### ISSUE TITLE
Filtering OID

### ISSUE THREAD

**Issue by Pelleplast** [etingof/snmpfwd#36]
Hi!
So i'm new to this and i'm trying to install OIDfiltering. When i tried to run the testcommands i got this message : sysLocation.0: Unknown Object Identifier (Sub-id not found: (top) -> sysLocation)
I've googled around but i can't seem to find a solution for it.

**Comment by etingof** [comment]
It's hard to figure out what's happening from your report...

If you are running `snmpget` tool, perhaps you need to specify or pre-load `SNMPv2-MIB` e.g. `SNMPv2-MIB::sysLocation.0`.

**Comment by Pelleplast** [comment]
That's the output i get when i try to run the commands to test the configuration just after copying in your example config. Do you require to install snmpd to be able to run the snmp requests?

**Comment by etingof** [comment]
No snmpd is required.

The error you report seems to happen on the client side, that is it would fail in the same way even if you run it without snmpfwd installed.

To reiterate, I suspect you need to call snmpget like this:

```
$ snmpget -v2c -c public 127.0.0.1 SNMPv2c-MIB::sysLocation.0
```

But pasting your exact command and error message would help.
