### ISSUE TITLE
Documentation - Snmplabs.com is unreachable

### ISSUE THREAD

**Issue by lucascmreis** [etingof/snmpfwd#53]
Hey there! 
That's a very helpful tool, for administrate legacy systems!  Thanks a lot! 
Well, I've tried to get  snmplabs.com page and looks like it's not available anymore.. 
Is that temporary or the domain have changed?
Thanks!

**Comment by henrythorpe** [comment]
Lucas - you can build the documentation...
1. clone the repo
2. cd snmpfwd/docs
3. make html
start with the index.html in the build/html directory.

**Comment by stappersg** [comment]
Confirming that
```text
git clone https://github.com/etingof/snmpfwd
cd snmpfwd/docs/
make html
```
works on a Linux system that has Sphinx installed.

Next
```text
firefox build/html/index.html 
```
to read it.


About the
> Well, I've tried to get snmplabs.com page and looks like it's not available anymore.
> Is that temporary or the domain have changed?

That is _How can I help?_  with many spelling errors  :smiley:

**Comment by lucascmreis** [comment]
Thanks!! It was very helpful!!
